FAKE_ANSWER = {
	"num_not_exist.wav": "So dien thoai cua ban khong the su dung dich vu nay",
	"ask_card.wav": "Ban co 2 loai the, the ghi no quoc te, the tin dung, the ghi no noi dia",
	"lock_debit.wav": "The ghi no quoc te cua ban da bi khoa",
	"lock_credit.wav": "The tin dung cua ban da bi khoa",
	"lock_atm.wav": "The ghi no noi dia cua ban da bi khoa",
	"credit_due.wav": "Ban da tra tien qua han 15 ngay thang nay, lai suat hien tai la 5%",
	"unknown.wav": "Xin loi, minh chua hieu duoc y muon cua ban, ban co muon ket noi voi nhan vien tu van truc tiep khong",
	"calling_person.wav": "Ban dang duoc ket noi voi nhan vien tu van....",
	"hello.wav": "Chao ban, minh la Stifr, tro ly ao cua VPBank, minh co the giup gi duoc cho ban",
	"require_login.wav": "Xin loi, de su dung duoc dich vu nay ban can phai xac thuc nguoi dung, ban nhac lai cau \"Xin chao Stifr\" de minh xac thuc giong noi cua ban nhe",
	"not_success.wav": "Xin loi, giong noi cua ban khong phu hop voi chu tai khoan nay",
	"ask_again.wav": "Minh con co the giup gi duoc cho ban khong nhi?",
	"regist_card.wav": "Co hai loai the thanh toan ban co the dang ky. The ghi no quoc te va the tin dung, ban muon dang ky mo the nao nhi?",
	"regist_credit.wav": "Xin loi minh chua the giup ban dang ky the tin dung duoc, ban co muon minh lien he voi nhan vien tu van khong?",
	"ask_name.wav": "Ban cho minh xin ten ban voi",
	"ask_phone.wav": "Cho minh xin so dien thoai cua ban voi",
	"ask_idcard.wav": "Ban cho minh thong tin ve so chung minh thu nhan dan hoac ho chieu nhe",
	"reask_name.wav": "Minh chua nghe ro ten cua ban, ban nhac lai ho minh voi nhe",
	"reask_phone.wav": "Xin loi ban, ban nhac lai so dien thoai giup minh duoc khong",
	"reask_idcard.wav": "Ban nhac lai mot lan nua so chung minh thu ho minh voi nhe, minh chua nghe ro",
	"filled_form.wav": "Minh da nhan duoc du thong tin cua ban, nhan vien tu van ben minh se lien lac lai voi ban nhe",
}